### ISSUE TITLE
Obico on Creality Ender KE: Webcam not seen, but works everywhere else.

### ISSUE THREAD

**Issue by Jeppedy** [TheSpaghettiDetective/moonraker-obico#109]
Running an Ender 3 V3 KE with Klipper/Mainsail

I'm new to Klipper, but not Linux or computers; just getting used to the slightly constrained linux environment on the Creality Klipper instance.
I used the Creaity Helper script to install Obico for Moonraker.
Obico itself works fine, but no web cam image.
Mainsail, OctoApp and others which can all see the web cam.

Obico Moonraker logs report the following, attached.

And to be clear: run.sh is there, but it won't run due to Bash not being installed, then the path issues; maybe other issues too??
When Bash wasn't available, I installed bash via Opkg.
Then, Bash is not in the place the shebang line expects it.
I can't run the run.sh by hand, so something is wrong, and at this point, I'm headed down a rabbit hole.

Any suggestions?  My relevant log entries below: 
```
2024-10-30 11:58:40,087     ERROR  obico.webcam_stream - Failed to find ffmpeg h264 encoder. Exception: [Errno 2] No such file or directory: '/usr/data/moonraker-obico/moonraker_obico/bin/ffmpeg/run.sh'
Traceback (most recent call last):
  File "/usr/data/moonraker-obico/moonraker_obico/webcam_stream.py", line 74, in find_ffmpeg_h264_encoder
    ffmpeg_test_proc = subprocess.Popen(ffmpeg_cmd.split(' '), stdout=FNULL, stderr=FNULL)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lib/python3.11/subprocess.py", line 1026, in __init__
  File "/opt/lib/python3.11/subprocess.py", line 1950, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/usr/data/moonraker-obico/moonraker_obico/bin/ffmpeg/run.sh'
Traceback (most recent call last):
  File "/usr/data/moonraker-obico/moonraker_obico/webcam_stream.py", line 74, in find_ffmpeg_h264_encoder
    ffmpeg_test_proc = subprocess.Popen(ffmpeg_cmd.split(' '), stdout=FNULL, stderr=FNULL)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lib/python3.11/subprocess.py", line 1026, in __init__
  File "/opt/lib/python3.11/subprocess.py", line 1950, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/usr/data/moonraker-obico/moonraker_obico/bin/ffmpeg/run.sh'
2024-10-31 12:01:38,827     ERROR  obico.utils - 
Traceback (most recent call last):
  File "/usr/data/moonraker-obico/moonraker_obico/app.py", line 214, in event_loop
    self._process_event(event)
  File "/usr/data/moonraker-obico/moonraker_obico/app.py", line 226, in _process_event
    self._on_moonrakerconn_event(event)
  File "/usr/data/moonraker-obico/moonraker_obico/app.py", line 267, in _on_moonrakerconn_event
    self._received_klippy_update(event.data['result'])
  File "/usr/data/moonraker-obico/moonraker_obico/app.py", line 351, in _received_klippy_update
    self.set_current_print(printer_state)
  File "/usr/data/moonraker-obico/moonraker_obico/app.py", line 288, in set_current_print
    printer_state.set_obico_g_code_file_id(self.find_obico_g_code_file_id(printer_state.status, file_metadata))
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/data/moonraker-obico/moonraker_obico/app.py", line 304, in find_obico_g_code_file_id
    resp = self.server_conn.send_http_request('POST', '/api/v1/octo/g_code_files/', timeout=60, data=g_code_data, raise_exception=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/data/moonraker-obico/moonraker_obico/server_conn.py", line 179, in send_http_request
    resp.raise_for_status()
  File "/usr/data/moonraker-obico-env/lib/python3.11/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://app.obico.io/api/v1/octo/g_code_files/
2024-10-31 12:03:32,505     ERROR  obico.webcam_stream - Failed to find ffmpeg h264 encoder. Exception: [Errno 2] No such file or directory: '/usr/data/moonraker-obico/moonraker_obico/bin/ffmpeg/run.sh'
Traceback (most recent call last):
  File "/usr/data/moonraker-obico/moonraker_obico/webcam_stream.py", line 74, in find_ffmpeg_h264_encoder
    ffmpeg_test_proc = subprocess.Popen(ffmpeg_cmd.split(' '), stdout=FNULL, stderr=FNULL)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lib/python3.11/subprocess.py", line 1026, in __init__
  File "/opt/lib/python3.11/subprocess.py", line 1950, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/usr/data/moonraker-obico/moonraker_obico/bin/ffmpeg/run.sh'
Traceback (most recent call last):
  File "/usr/data/moonraker-obico/moonraker_obico/webcam_stream.py", line 74, in find_ffmpeg_h264_encoder
    ffmpeg_test_proc = subprocess.Popen(ffmpeg_cmd.split(' '), stdout=FNULL, stderr=FNULL)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/lib/python3.11/subprocess.py", line 1026, in __init__
  File "/opt/lib/python3.11/subprocess.py", line 1950, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/usr/data/moonraker-obico/moonraker_obico/bin/ffmpeg/run.sh'
```

**Comment by kennethjiang** [comment]
Sorry for the delay. This is not a bug. Please come to our discord server to discuss. https://obico.io/discord/
