### ISSUE TITLE
Mainailos - Janus quit! because of undefined symbol in libsoup-2.4.so.1

### ISSUE THREAD

**Issue by maartendirickx** [TheSpaghettiDetective/moonraker-obico#82]
Updating my mainsailos installation after half a year. Everything works, except for Janus. 

I'm running into an error: precomplied/rpi.debian.10.32-bit/lib/libsoup-2.4.so.1: undefined symbol.

I see the rpi.debian.10.32-bit is a symlink to rpi.debian.11.32-bit. Is Debian Buster no longer supported?

```
Oct 15 18:18:09 mainsailos python3[4375]: 2023-10-15 18:18:09,247     DEBUG  obico.janus - JANUS: /home/pi/moonraker-obico/moonraker_obico/bin/janus/precomplied/rpi.debian.10.32-bit/bin/janus: symbol lookup error: /home/pi/moonraker-obico/moonraker_obico/bin/janus/precomplied/rpi.debian.10.32-bit/lib/libsoup-2.4.so.1: undefined symbol: g_file_info_get_modification_date_time
Oct 15 18:18:09 mainsailos python3[4375]: 2023-10-15 18:18:09,252     ERROR  backoff - Giving up run_janus(...) after 5 tries (Exception: Janus quit! This should not happen. Exit code: 127)
Oct 15 18:18:09 mainsailos python3[4375]: 2023-10-15 18:18:09,253     ERROR  obico.utils -
Oct 15 18:18:09 mainsailos python3[4375]: Traceback (most recent call last):
Oct 15 18:18:09 mainsailos python3[4375]:   File "/home/pi/moonraker-obico/moonraker_obico/janus.py", line 85, in run_janus_forever
Oct 15 18:18:09 mainsailos python3[4375]:     run_janus()
Oct 15 18:18:09 mainsailos python3[4375]:   File "/home/pi/moonraker-obico-env/lib/python3.7/site-packages/backoff/_sync.py", line 94, in retry
Oct 15 18:18:09 mainsailos python3[4375]:     ret = target(*args, **kwargs)
Oct 15 18:18:09 mainsailos python3[4375]:   File "/home/pi/moonraker-obico/moonraker_obico/janus.py", line 81, in run_janus
Oct 15 18:18:09 mainsailos python3[4375]:     raise Exception('Janus quit! This should not happen. Exit code: {}'.format(self.janus_proc.returncode))
Oct 15 18:18:09 mainsailos python3[4375]: Exception: Janus quit! This should not happen. Exit code: 127
```

**Comment by kennethjiang** [comment]
Original Buster is still supported. But this error looks like a broken dependency resulted from upgrading system libs.

This is more like a setup issue than a bug. Please come to our discord channel to get speedy help: https://obico.io/discord-obico-klipper/
